//ARMA Vanilla
"Cane1",
"Cane2",
"Ficus_Bush_1",
"Ficus_Bush_2",
"Ficus_Bush_3",
"Oleander1",
"Oleander2",
"Oleander_White",

//ARMA Malden
"Vinifera",
"Opuntiaficusindica",

//ARMA APEX
"Calochlaena",
"Cestrum",
"Colored_red",
"Colored_yellow",
"Cycas",
"FicusC2d_tanoa",
"Gardenia_dec_01",
"Gardenia_dec_02",
"Gardenia",
"Leucaena_shrub",
"NeriumO2d_tanoa",
"PiperMeth",
"Rhizophora_shrub",

//ARMA LIVONIA
"Betula_nana",
"Caragana_arborescens",
"Corylus_heterophylla_1",
"Corylus_heterophylla_2",
"FagusSylvatica_b_1f",
"Phragmites_australis",
"PiceaAbies_b_1f",
"PiceaAbies_b_1fb",
"prunusSpinosa_1s",
"prunusSpinosa_2s",
"rosaCanina_1s",
"rosaCanina_2s",
"sambucusNigra_1s",
"sambucusNigra_2s",
