name = "Metis_Nature"
mainprefix = "z"
prefix = "mts"
author = "Timi007"

[files]
include = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "mts_picture.paa",
    "mts_nature_logo_small.paa",
    "mts_nature_logo_over_small.paa",
    "meta.cpp"
]

[signing]
authority = "mts_nature"

[version]
path = "addons/nature/script_version.hpp"
git_hash = 0

[asc]
enabled = true
exclude = [
    "/initsettings.sqf",
    "/initkeybinds.sqf",
    "/xeh_prep.sqf",
]

[hemtt.config]
preset = "Hemtt"

[hemtt.release]
folder = "Metis_Nature"

[hemtt.launch.default]
workshop = []
